// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogArticle: typeof import('./src/components/FrontSeat/Blog/BlogArticle.vue')['default']
    BlogBanner: typeof import('./src/components/FrontSeat/Blog/BlogBanner.vue')['default']
    BlogIndexItem: typeof import('./src/components/FrontSeat/Blog/BlogIndexItem.vue')['default']
    BlogRecommend: typeof import('./src/components/FrontSeat/Blog/BlogRecommend.vue')['default']
    BlogTag: typeof import('./src/components/FrontSeat/aside/BlogTag.vue')['default']
    FooterView: typeof import('./src/components/FrontSeat/Layout/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/FrontSeat/Layout/HeaderView.vue')['default']
    LoginAuth: typeof import('./src/components/FrontSeat/auth/LoginAuth.vue')['default']
    Recommend: typeof import('./src/components/FrontSeat/Blog/Recommend.vue')['default']
    RegisterAuth: typeof import('./src/components/FrontSeat/auth/RegisterAuth.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserPersonalInfo: typeof import('./src/components/FrontSeat/aside/UserPersonalInfo.vue')['default']
    WebSiteInfo: typeof import('./src/components/FrontSeat/aside/WebSiteInfo.vue')['default']
    WebSiteNotice: typeof import('./src/components/FrontSeat/aside/WebSiteNotice.vue')['default']
  }
}
