// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogArticle: typeof import('./src/components/FrontSeat/Blog/BlogArticle.vue')['default']
    BlogNotice: typeof import('./src/components/FrontSeat/aside/BlogNotice.vue')['default']
    BlogPersonalInfo: typeof import('./src/components/FrontSeat/aside/BlogPersonalInfo.vue')['default']
    BlogTag: typeof import('./src/components/FrontSeat/Blog/BlogTag.vue')['default']
    FooterView: typeof import('./src/components/FrontSeat/Layout/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/FrontSeat/Layout/HeaderView.vue')['default']
    LoginAuth: typeof import('./src/components/FrontSeat/auth/LoginAuth.vue')['default']
    RegisterAuth: typeof import('./src/components/FrontSeat/auth/RegisterAuth.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserNotice: typeof import('./src/components/FrontSeat/aside/UserNotice.vue')['default']
    UserPersonalInfo: typeof import('./src/components/FrontSeat/aside/UserPersonalInfo.vue')['default']
    WebSiteInfo: typeof import('./src/components/FrontSeat/aside/WebSiteInfo.vue')['default']
    WebSiteNotice: typeof import('./src/components/FrontSeat/aside/WebSiteNotice.vue')['default']
  }
}
